{% set name = "google-cloud-logging" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8932ac382eee6af85cd08400a77586dd3139fbf40b61db757c4c492490899741

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - google-api-core-grpc >=1.22.0,<2.0.0dev
    - google-cloud-core >=1.4.1,<2.0dev
    - proto-plus >=1.11.0
    - python >=3.6

test:
  imports:
    - google.cloud.logging
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-logging
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Stackdriver Logging API client library
  description: "The Stackdriver Logging API writes log entries and manages your Stackdriver Logging configuration.\nSee the [usage guide](https://googleapis.dev/python/logging/latest/usage.html)."

  doc_url: https://googleapis.dev/python/logging/latest/index.html
  dev_url: https://github.com/googleapis/python-logging

extra:
  recipe-maintainers:
    - parthea
    - xylar
