{% set name = "google-cloud-logging" %}
{% set version = "3.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e53205510652df5794f04176ea395c6cc1862a8e8d2bd0678370a2defeb74bff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - opentelemetry-api >=1.0.0
    - python >=3.7
    - google-api-core >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    - google-cloud-appengine-logging >=0.1.0,<2.0.0dev
    - google-cloud-audit-log >=0.1.0,<1.0.0dev
    - google-cloud-core >=2.0.0,<3.0.0dev
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.cloud.logging
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-logging
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Stackdriver Logging API client library
  description: "The Stackdriver Logging API writes log entries and manages your Stackdriver Logging configuration.\nSee the [usage guide](https://googleapis.dev/python/logging/latest/usage.html)."

  doc_url: https://googleapis.dev/python/logging/latest/index.html
  dev_url: https://github.com/googleapis/python-logging

extra:
  recipe-maintainers:
    - parthea
    - xylar
